// File generated by FlutterFire CLI.
// This is a TEMPLATE file - replace with actual values from Firebase Console
// Run: flutterfire configure --project=your-project-id

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example: await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Config web project trash2heal
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0h8yZI6UuP9VIsJt49GrZj7vKO6xPes',
    appId: '1:503352459716:web:87e2d08b2be461aa216491',
    messagingSenderId: '503352459716',
    projectId: 'trash2heal',
    authDomain: 'trash2heal.firebaseapp.com',
    storageBucket: 'trash2heal.firebasestorage.app',
    measurementId: 'G-HGDGDBF7LG',
  );

  // Android config (mengikuti project yang sama jika diperlukan)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx0h8yZI6UuP9VIsJt49GrZj7vKO6xPes',
    appId: '1:503352459716:web:87e2d08b2be461aa216491',
    messagingSenderId: '503352459716',
    projectId: 'trash2heal',
    storageBucket: 'trash2heal.firebasestorage.app',
  );

  // iOS config (placeholder; update jika build iOS admin)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx0h8yZI6UuP9VIsJt49GrZj7vKO6xPes',
    appId: '1:503352459716:web:87e2d08b2be461aa216491',
    messagingSenderId: '503352459716',
    projectId: 'trash2heal',
    storageBucket: 'trash2heal.firebasestorage.app',
    iosClientId: 'trash2heal-ios-client',
    iosBundleId: 'com.trash2heal.admin',
  );

  // macOS config (placeholder; update jika diperlukan)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx0h8yZI6UuP9VIsJt49GrZj7vKO6xPes',
    appId: '1:503352459716:web:87e2d08b2be461aa216491',
    messagingSenderId: '503352459716',
    projectId: 'trash2heal',
    storageBucket: 'trash2heal.firebasestorage.app',
    iosClientId: 'trash2heal-macos-client',
    iosBundleId: 'com.trash2heal.admin',
  );
}
